// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.34.0
// source: threat.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ThreatAssessmentService_AssessRequest_FullMethodName = "/threat.v1.ThreatAssessmentService/AssessRequest"
)

// ThreatAssessmentServiceClient is the client API for ThreatAssessmentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ThreatAssessmentServiceClient interface {
	AssessRequest(ctx context.Context, in *ThreatRequest, opts ...grpc.CallOption) (*ThreatResponse, error)
}

type threatAssessmentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewThreatAssessmentServiceClient(cc grpc.ClientConnInterface) ThreatAssessmentServiceClient {
	return &threatAssessmentServiceClient{cc}
}

func (c *threatAssessmentServiceClient) AssessRequest(ctx context.Context, in *ThreatRequest, opts ...grpc.CallOption) (*ThreatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ThreatResponse)
	err := c.cc.Invoke(ctx, ThreatAssessmentService_AssessRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ThreatAssessmentServiceServer is the server API for ThreatAssessmentService service.
// All implementations must embed UnimplementedThreatAssessmentServiceServer
// for forward compatibility.
type ThreatAssessmentServiceServer interface {
	AssessRequest(context.Context, *ThreatRequest) (*ThreatResponse, error)
	mustEmbedUnimplementedThreatAssessmentServiceServer()
}

// UnimplementedThreatAssessmentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedThreatAssessmentServiceServer struct{}

func (UnimplementedThreatAssessmentServiceServer) AssessRequest(context.Context, *ThreatRequest) (*ThreatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AssessRequest not implemented")
}
func (UnimplementedThreatAssessmentServiceServer) mustEmbedUnimplementedThreatAssessmentServiceServer() {
}
func (UnimplementedThreatAssessmentServiceServer) testEmbeddedByValue() {}

// UnsafeThreatAssessmentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ThreatAssessmentServiceServer will
// result in compilation errors.
type UnsafeThreatAssessmentServiceServer interface {
	mustEmbedUnimplementedThreatAssessmentServiceServer()
}

func RegisterThreatAssessmentServiceServer(s grpc.ServiceRegistrar, srv ThreatAssessmentServiceServer) {
	// If the following call pancis, it indicates UnimplementedThreatAssessmentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ThreatAssessmentService_ServiceDesc, srv)
}

func _ThreatAssessmentService_AssessRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ThreatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ThreatAssessmentServiceServer).AssessRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ThreatAssessmentService_AssessRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ThreatAssessmentServiceServer).AssessRequest(ctx, req.(*ThreatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ThreatAssessmentService_ServiceDesc is the grpc.ServiceDesc for ThreatAssessmentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ThreatAssessmentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "threat.v1.ThreatAssessmentService",
	HandlerType: (*ThreatAssessmentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AssessRequest",
			Handler:    _ThreatAssessmentService_AssessRequest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "threat.proto",
}
