// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v7.34.0
// source: threat.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ThreatRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Uri             string                 `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	IsAuthenticated bool                   `protobuf:"varint,2,opt,name=is_authenticated,json=isAuthenticated,proto3" json:"is_authenticated,omitempty"`
	SourceIp        string                 `protobuf:"bytes,3,opt,name=source_ip,json=sourceIp,proto3" json:"source_ip,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ThreatRequest) Reset() {
	*x = ThreatRequest{}
	mi := &file_threat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThreatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThreatRequest) ProtoMessage() {}

func (x *ThreatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_threat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThreatRequest.ProtoReflect.Descriptor instead.
func (*ThreatRequest) Descriptor() ([]byte, []int) {
	return file_threat_proto_rawDescGZIP(), []int{0}
}

func (x *ThreatRequest) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *ThreatRequest) GetIsAuthenticated() bool {
	if x != nil {
		return x.IsAuthenticated
	}
	return false
}

func (x *ThreatRequest) GetSourceIp() string {
	if x != nil {
		return x.SourceIp
	}
	return ""
}

type ThreatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ThreatLevel   int32                  `protobuf:"varint,1,opt,name=threat_level,json=threatLevel,proto3" json:"threat_level,omitempty"` // 0-10 scale
	Reasons       []string               `protobuf:"bytes,2,rep,name=reasons,proto3" json:"reasons,omitempty"`                             // e.g., ["unauthenticated", "blacklisted_ip"]
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThreatResponse) Reset() {
	*x = ThreatResponse{}
	mi := &file_threat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThreatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThreatResponse) ProtoMessage() {}

func (x *ThreatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_threat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThreatResponse.ProtoReflect.Descriptor instead.
func (*ThreatResponse) Descriptor() ([]byte, []int) {
	return file_threat_proto_rawDescGZIP(), []int{1}
}

func (x *ThreatResponse) GetThreatLevel() int32 {
	if x != nil {
		return x.ThreatLevel
	}
	return 0
}

func (x *ThreatResponse) GetReasons() []string {
	if x != nil {
		return x.Reasons
	}
	return nil
}

var File_threat_proto protoreflect.FileDescriptor

const file_threat_proto_rawDesc = "" +
	"\n" +
	"\fthreat.proto\x12\tthreat.v1\"i\n" +
	"\rThreatRequest\x12\x10\n" +
	"\x03uri\x18\x01 \x01(\tR\x03uri\x12)\n" +
	"\x10is_authenticated\x18\x02 \x01(\bR\x0fisAuthenticated\x12\x1b\n" +
	"\tsource_ip\x18\x03 \x01(\tR\bsourceIp\"M\n" +
	"\x0eThreatResponse\x12!\n" +
	"\fthreat_level\x18\x01 \x01(\x05R\vthreatLevel\x12\x18\n" +
	"\areasons\x18\x02 \x03(\tR\areasons2_\n" +
	"\x17ThreatAssessmentService\x12D\n" +
	"\rAssessRequest\x12\x18.threat.v1.ThreatRequest\x1a\x19.threat.v1.ThreatResponseB=Z;github.com/kuadrant/threat-assessment-service/pkg/threat/v1b\x06proto3"

var (
	file_threat_proto_rawDescOnce sync.Once
	file_threat_proto_rawDescData []byte
)

func file_threat_proto_rawDescGZIP() []byte {
	file_threat_proto_rawDescOnce.Do(func() {
		file_threat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_threat_proto_rawDesc), len(file_threat_proto_rawDesc)))
	})
	return file_threat_proto_rawDescData
}

var file_threat_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_threat_proto_goTypes = []any{
	(*ThreatRequest)(nil),  // 0: threat.v1.ThreatRequest
	(*ThreatResponse)(nil), // 1: threat.v1.ThreatResponse
}
var file_threat_proto_depIdxs = []int32{
	0, // 0: threat.v1.ThreatAssessmentService.AssessRequest:input_type -> threat.v1.ThreatRequest
	1, // 1: threat.v1.ThreatAssessmentService.AssessRequest:output_type -> threat.v1.ThreatResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_threat_proto_init() }
func file_threat_proto_init() {
	if File_threat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_threat_proto_rawDesc), len(file_threat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_threat_proto_goTypes,
		DependencyIndexes: file_threat_proto_depIdxs,
		MessageInfos:      file_threat_proto_msgTypes,
	}.Build()
	File_threat_proto = out.File
	file_threat_proto_goTypes = nil
	file_threat_proto_depIdxs = nil
}
